export const spanishTranslation = {
  calibrationModal: {
    title: "Calibración",
    text1: "Nuestro algoritmo se basa en la información introducida sobre su Presión Arterial (PA) como referencia para calcular los resultados exactos del paciente, tal es así, que le solicitamos que indique cuál es su estado de PA normal conocido siendo los valores posibles los que se definen a continuación:",
    text2: "Normal: PAS 90 - 120\nPrehipertensión: PAS 120 - 140\nHipertensión: PAS 140 - 180",
    text3: "1- Si ud es hipertenso y está tomando medicación entonces debe indicar el estado de Prehipertensión.\n2- Si no conoce en absoluto la PA, se recomienda utilizar el tensiómetro para realizar una medición inicial (calibración) y a continuación, utilizar ese estado de referencia para todas las lecturas posteriores.",
    subtitle: "Importante",
    text4: "Vitals posee un software de medición de la frecuencia del pulso sin contacto basado en video con una función de reconocimiento facial diseñado para medir y mostrar en tiempo real la frecuencia del pulso de adultos. Este sistema utiliza cámaras para detectar el rostro del usuario y obtiene datos continuos de la imagen del rostro, con procesamiento de señales y algoritmo para calcular la frecuencia del pulso. El software está diseñado para instalarse en dispositivos móviles/portátiles/computadoras comerciales equipados con cámaras. Se puede implementar en plataformas Android, iOS y Windows. Está destinado a mediciones puntuales no invasivas de la frecuencia del pulso cuando el sujeto está quieto. Esta solución no está diseñada para su uso en pacientes con arritmias cardíacas conocidas o sospechadas. Si bien Vitals se puede utilizar para la atención sanitaria general, no está diseñado para tratar a pacientes. Los resultados de la medición de la frecuencia del pulso proporcionados por Vitals deben complementar, pero no reemplazar, la atención médica y/o la medicación profesional habitual del usuario. Si se detectan anomalías durante la medición con Vitals, se recomienda a los usuarios que consulten a un profesional médico. Vitals está indicado para su uso en seres humanos de 18 años o más que no requieren cuidados críticos. Este software no debe ser el método principal ni el único para evaluar la salud de un individuo. BCare Vitals es la plataforma de Telemedicina en modelo SaaS (Software como Servicio) registrado en ANMAT con número de trámite TAD IF-2024-129009398-APN-DEYRPM#ANMAT, con toma de signos vitales en línea, para brindar la mejor experiencia en consultas médicas a distancia. La plataforma permite que médicos y pacientes puedan agendar sus citas o realizar consultas espontáneas con servicios de emergencias, compartan documentos antes y después de la tele-consulta, y también se facilita la gestión de la historia clínica de manera completa e integrada. El componente posee registro FDA (Administración de Alimentos y Medicamentos - FDA por su sigla en inglés - Food and Drug Administration) que es la agencia del Gobierno de Estados Unidos responsable de la regulación de éstos, incluyendo además, cosméticos, aparatos médicos, productos biológicos y derivados sanguíneos bajo la regulación sobre Software para medición mediante cámara óptica para pulso cardíaco y respiratorio."
  },
};